- name: Config Wifi APs
  hosts: wifi
  roles:
    - gekmihesg.openwrt

  tasks:
    - name: copy authorized keys
      ansible.builtin.copy:
        dest: "/etc/dropbear/authorized_keys"
        content: "{{ lookup('ansible.builtin.url', 'https://github.com/krelinga.keys', split_lines=false) }}"
        owner: root
        group: root
        mode: "0600"

    # uci add_list network.lan.dns='10.86.14.1'
    # - name: Disable local DHCP server on LAN interface
    #   uci:
    #     command: add_list
