- name: Check required variables
  ansible.builtin.assert:
    that:
      - "item | length > 0"
    fail_msg: "The variable '{{ item }}' must be defined and not empty."
  loop:
    - tls_cert_push_truenas_host
    - tls_cert_push_truenas_api_key

- name: Upload Certificate
  truenas_cert_upload:
    host: "{{ tls_cert_push_truenas_host }}"
    api_key: "{{ tls_cert_push_truenas_api_key }}"
    certificate: "{{ lookup('file', '/nas/certs/live/i.krel.ing/fullchain.pem') }}"
    private_key: "{{ lookup('file', '/nas/certs/live/i.krel.ing/privkey.pem') }}"