- name: Fetch TLS cert
  hosts: nas-docker
  roles:
    - tls_cert_fetch

- name: Push TLS cert to truenas
  hosts: localhost
  vars:
    tls_cert_push_platform: truenas
    tls_cert_push_truenas_host: "truenas.i.krel.ing"
    tls_cert_push_truenas_api_key: "{{ lookup('bitwarden.secrets.lookup', '74662f7f-26b7-4538-af7e-b2d1004355a1') }}"
  roles:
    - tls_cert_push

- name: Push TLS cert to pve
  hosts: pve
  vars:
    tls_cert_push_platform: pve
  roles:
    - tls_cert_push
