- name: Fetch TLS cert
  hosts: nas-docker
  roles:
    - tls_cert_fetch

- name: Push TLS cert to truenas
  hosts: truenas
  roles:
    - tls_cert_push

- name: Push TLS cert to pve
  hosts: pve
  roles:
    - tls_cert_push

- name: Push TLS cert to gateway
  hosts: gateway
  gather_facts: false  # TODO: it would be nice to have this at inventory level.
  roles:
    - tls_cert_push

# TODO: when this playbook is run manually from semaphore, restarting the caddy container causes the UI to hang.
# I should sweep this up when I consolidate critical infrastructure onto my infra pi.
- name: Restart Caddy
  hosts: nas-docker
  tasks:
    - name: Restart caddy
      community.docker.docker_container:
        name: caddy
        state: started
        restart: yes
      when: tls_cert_fetch.changed
