- name: Fetch TLS cert
  hosts: nas-docker
  roles:
    - tls_cert_fetch

- name: Push TLS cert to truenas
  hosts: localhost
  vars:
    tls_cert_push_platform: truenas
    tls_cert_push_truenas_host: "truenas.i.krel.ing"
    tls_cert_push_truenas_api_key: "{{ lookup('bitwarden.secrets.lookup', '74662f7f-26b7-4538-af7e-b2d1004355a1') }}"
  roles:
    - tls_cert_push

- name: Push TLS cert to pve
  hosts: pve
  vars:
    tls_cert_push_platform: pve
  roles:
    - tls_cert_push

- name: Push TLS cert to gateway
  hosts: localhost
  vars:
    tls_cert_push_platform: opnsense
    tls_cert_push_opnsense_host: "gateway.i.krel.ing"
    tls_cert_push_opnsense_api_key: "{{ lookup('bitwarden.secrets.lookup', '20615609-4d51-472f-bb43-b2d40029e520') }}"
    tls_cert_push_opnsense_api_secret: "{{ lookup('bitwarden.secrets.lookup', '89d647a1-fde8-447c-88a9-b2d40029fc0c') }}"
    tls_cert_push_opnsense_web_user_name: krelinga
    tls_cert_push_opnsense_web_password: "{{ lookup('bitwarden.secrets.lookup', '43a0ff9b-5a9e-4167-842b-b2d5002ec71a') }}"
  roles:
    - tls_cert_push

# TODO: when this playbook is run manually from semaphore, restarting the caddy container causes the UI to hang.
# I should sweep this up when I consolidate critical infrastructure onto my infra pi.
- name: Restart Caddy
  hosts: nas-docker
  tasks:
    - name: Restart caddy
      community.docker.docker_container:
        name: caddy
        state: started
        restart: yes
      # when: tls_cert_fetch.changed