roles:
  - name: geerlingguy.docker
  - name: geerlingguy.pip
  - name: elliotweiser.osx-command-line-tools
  - name: gekmihesg.openwrt

collections:
  - name: geerlingguy.mac
  - name: arensb.truenas