roles:
  - name: geerlingguy.docker
  - name: geerlingguy.pip
  - name: elliotweiser.osx-command-line-tools
  - name: gekmihesg.openwrt
  - name: nvidia.nvidia_driver

collections:
  - name: geerlingguy.mac
  - name: arensb.truenas
  - name: community.docker
  - name: community.general
  - name: ansible.posix
  - name: community.proxmox
  - name: prometheus.prometheus
