people:
  "Alec Warner":
    birthday: "1984-09-20"
  "Amanda Baxley":
    birthday: "1986-07-13"
  "Andrew Bell":
    birthday: "2015-04-03"
    notice: 14
  "Barbara Smyth":
    birthday: "1946-01-24"
  "Catherine Minser":
    birthday: "2019-01-18"
    notice: 14
  "Dad":
    birthday: "1955-07-13"
    notice: 14
  "Danny Groben":
    birthday: "0000-11-14"
  "Eleanor Slade":
    birthday: "2025-08-14"
    notice: 14
  "Elizabeth Minser":
    birthday: "2019-01-18"
    notice: 14
  "Erin Bigelow":
    birthday: "1984-07-17"
  "Francesca Slade":
    birthday: "1988-10-04"
  "Fred Clifford":
    birthday: "1984-01-06"
  "Graham Bigelow":
    birthday: "2017-11-30"
    notice: 14
  "Jeff Bell":
    birthday: "1984-11-23"
  "Jill Kennicott":
    birthday: "0000-07-31"
  "Jill Kreling":
    birthday: "1986-09-13"
  "Jon Blowers":
    birthday: "1984-02-01"
  "Logan Geimer":
    birthday: "2017-08-13"
    notice: 14
  "Mackenzie Bell":
    birthday: "2018-06-02"
    notice: 14
  "Maggie Matthews":
    birthday: "2019-04-23"
    notice: 14
  "Marc Baxley":
    birthday: "1984-11-26"
    notice: 14
  "Martel Thompson":
    birthday: "1981-11-12"
  "Matt Geimer":
    birthday: "1982-04-14"
  "Mia Murphy":
    birthday: "1984-12-14"
  "Michelle O'Connor":
    birthday: "1981-06-04"
  "Molly Rossow":
    birthday: "0000-10-09"
  "Mom":
    birthday: "1957-05-16"
    notice: 14
  "Nicole Smith":
    birthday: "0000-02-01"
  "Nyx":
    birthday: "1977-09-17"
  "Oscar Sirota":
    birthday: "2023-02-06"
    notice: 14
  "Owen Geimer":
    birthday: "2019-03-16"
    notice: 14
  "Pat Bigelow":
    birthday: "1984-11-16"
  "Robin Blair":
    birthday: "1984-07-25"
  "Sam Dean":
    birthday: "1989-10-27"
  "Suzy":
    birthday: "1981-07-16"
    notice: 30
  "Tricia Groben":
    birthday: "1981-02-07"
  "Owen Sirota":
    birthday: "2026-08-11"
    notice: 14
