- name: Ping
  hosts: slothmini
  gather_facts: false
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print Message
      ansible.builtin.debug:
        msg: Ping Finished
