- name: Create Caddy volumes
  community.docker.docker_volume:
    name: "{{ item }}"
    state: present
  loop:
    - caddy_data
    - caddy_config

- name: Ensure caddy_certs volume exists
  community.docker.docker_volume:
    name: caddy_certs
    state: present
    driver: local
    driver_options:
      type: cifs
      device: "//truenas.i.krel.ing/certs"
      # mfsymlinks is needed because certbot creates symlinks in this volume
      o: "username=certs_deploy,password={{ vault.certs_deploy_smb_password }},file_mode=0440,dir_mode=0550,ro,vers=3.0,mfsymlinks"

- name: Create Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "/home/{{ ansible_user }}/Caddyfile"
    mode: '0644'
  vars:
    proxies: "{{ caddy_proxies }}"
    cert_path: "/nas/certs/live/i.krel.ing/fullchain.pem"
    private_key_path: "/nas/certs/live/i.krel.ing/privkey.pem"
  register: caddy_caddyfile

- name: Create docker container for Caddy
  community.docker.docker_container:
    name: caddy
    image: caddy:latest
    state: started
    restart_policy: unless-stopped
    restart: "{{ 'yes' if caddy_caddyfile.changed else 'no' }}"
    pull: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - "/home/{{ ansible_user }}/Caddyfile:/etc/caddy/Caddyfile:ro"
      - caddy_certs:/nas/certs:ro
