- name: Config
  hosts: dev

  roles:
    - ssh_server
    - git_client
    - role: geerlingguy.docker
      become: true
      vars:
        docker_users:
          - "{{ ansible_user }}"
    - cifs

  tasks:
    - name: ensure ~/.bws has the correct contents
      ansible.builtin.copy:
        content: |
          export BWS_ACCESS_TOKEN={{ lookup('bitwarden.secrets.lookup', '42b7b009-7eb6-4c88-a41b-b2cc004be88c') }}
          export DEV_SMB_PASSWORD={{ lookup('bitwarden.secrets.lookup', '1f341f46-846e-450f-8938-b2cc011bb849') }}
        dest: ~/.bws
        mode: '0600'

    - name: ensure .bashrc sources ~/.bws
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: "source ~/.bws"
        state: present

    - name: ensure dev smb share is mounted
      become: true
      ansible.posix.mount:
        boot: true
        fstype: cifs
        src: //truenas.i.krel.ing/dev
        path: /mnt/dev
        opts: "username=dev,password={{ lookup('bitwarden.secrets.lookup', '1f341f46-846e-450f-8938-b2cc011bb849') }},file_mode=0666,dir_mode=0777,rw"
        state: mounted

    - name: ensure /nas directory exists
      become: true
      ansible.builtin.file:
        path: /nas
        state: directory
        mode: '0755'

    - name: create /nas/dev symbolic link
      become: true
      ansible.builtin.file:
        src: /mnt/dev
        dest: /nas/dev
        state: link

    - name: Ensure certbot_certs volume exists
      community.docker.docker_volume:
        name: certbot_certs
        state: present
        driver: local
        driver_options:
          type: cifs
          device: "//truenas.i.krel.ing/certs"
          # mfsymlinks is needed because certbot creates symlinks in this volume
          o: "username=dev,password={{ lookup('bitwarden.secrets.lookup', '1f341f46-846e-450f-8938-b2cc011bb849') }},file_mode=0400,dir_mode=0500,ro,vers=3.0,mfsymlinks"