- name: Config
  hosts: infrapi

  roles:
    - ssh_server
    - role: geerlingguy.docker
      become: true
      vars:
        docker_users:
          - "{{ ansible_user }}"
    - cifs
    - role: semaphore
      vars:
        semaphore_port: 3000
        semaphore_web_root: "https://sem.i.krel.ing"
      tags: ["semaphore"]
    - role: gotify
      tags: ["gotify"]
    - role: caddy
      vars:
        caddy_proxies:
          - fqdn: sem.i.krel.ing
            real_host: infrapi.i.krel.ing
            real_port: 3000
          - fqdn: gotify.i.krel.ing
            real_host: infrapi.i.krel.ing
            real_port: 25006
      tags: ["semaphore", "gotify"]
    - tailscale_subnet_router
