- name: Config
  hosts: infrapi

  roles:
    - ssh_server
    - role: geerlingguy.docker
      become: true
      vars:
        docker_users:
          - "{{ ansible_user }}"
    - cifs
    - role: semaphore
      vars:
        semaphore_port: 3000
        semaphore_web_root: "https://sem.i.krel.ing"
      tags: ["semaphore"]
    - role: prom_server
      tags: ["prom_server"]
    - role: caddy
      vars:
        caddy_proxies:
          - fqdn: sem.i.krel.ing
            real_host: infrapi.i.krel.ing
            real_port: 3000
          - fqdn: exporter-sem.i.krel.ing
            real_host: infrapi.i.krel.ing
            real_port: 25007
          - fqdn: prom.i.krel.ing
            real_host: infrapi.i.krel.ing
            real_port: 9090
      tags: ["semaphore", "prom_server"]
    - tailscale_subnet_router
    - prometheus.prometheus.node_exporter
    - role: grafana_pdc
      tags: ["grafana_pdc"]
