- name: Config
  hosts: infrapi

  roles:
    - ssh_server
    - role: geerlingguy.docker
      become: true
      vars:
        docker_users:
          - "{{ ansible_user }}"
    - cifs
    - role: semaphore
      vars:
        semaphore_port: 3000
        semaphore_web_root: "https://sem.i.krel.ing"
