- name: Import Tailscale GPG key # noqa: command-instead-of-module
  become: true
  ansible.builtin.shell: |
    curl -fsSL https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.noarmor.gpg > /usr/share/keyrings/tailscale-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/tailscale-archive-keyring.gpg
  register: tailscale_subnet_router_gpg_key

- name: Install Tailscale apt repo # noqa: command-instead-of-module
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
  args:
    creates: /etc/apt/sources.list.d/tailscale.list
    executable: /bin/bash  # needed for 'set -o pipefail'
  register: tailscale_subnet_router_repo

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
  when: tailscale_subnet_router_repo.changed or tailscale_subnet_router_gpg_key.changed

- name: Install Tailscale
  become: true
  ansible.builtin.apt:
    name: tailscale
    update_cache: true
    state: present

- name: Enable IP forwarding (IPv4)
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: true

- name: Enable IP forwarding (IPv6)
  become: true
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    state: present
    reload: true

- name: Start and authenticate Tailscale
  become: true
  ansible.builtin.shell: >
    tailscale up --authkey={{ vault.tailscale_auth_key }}
    --advertise-routes=10.86.14.0/24
    --hostname={{ inventory_hostname }}
  args:
    creates: /var/lib/tailscale/tailscaled.state

- name: Enable and start tailscaled service
  become: true
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true
    state: started
