- name: Check if Git user email is already set
  command: 'git config user.email'
  register: git_user_email
  failed_when: false
  changed_when: false

- name: Set Git user email
  command: 'git config --global user.email "{{ vault.my_email }}"'
  when: git_user_email.stdout == ""

- name: Check if Git user name is already set
  command: 'git config user.name'
  register: git_user_name
  failed_when: false
  changed_when: false

- name: Set Git user name
  command: 'git config --global user.name "{{ vault.my_name }}"'
  when: git_user_name.stdout == ""
