- name: Config
  hosts: dev-pve

  roles:
    - tls_cert_push
    - role: pve_server
      vars:
        pve_server_api_host: "dev-pve.i.krel.ing" # TODO: use invenotry_hostname?
        pve_server_root_password: "{{ vault.dev_pve_root_password }}"
        pve_server_node: dev-pve
        pve_server_vms:
          - name: dev
            iso_url: "https://mirror.pilotfiber.com/ubuntu-iso/24.04.2/ubuntu-24.04.2-live-server-amd64.iso"
            vmid: 100
            mac_address: "BC:24:11:67:F3:B8"
            cores: 23
            cpuunits: 90  # take priority over the dev-docker vm if CPU gets busy.
            memory_mb: 112640
            disk_gb: 500
          - name: dev-docker
            iso_url: "https://mirror.pilotfiber.com/ubuntu-iso/24.04.2/ubuntu-24.04.2-live-server-amd64.iso"
            vmid: 101
            mac_address: "BC:24:11:67:F3:B9"
            cores: 23
            memory_mb: 112640
            disk_gb: 300
            cpuunits: 10  # defer to the dev vm if CPU gets busy.
