- name: Config
  hosts: nas-pve

  roles:
    - pve_server
    - ssh_server

  tasks:
    - name: Enable IOMMU
      ansible.builtin.lineinfile:
        path: "/etc/default/grub"
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on"'
        state: present
      notify: Update grub

    - name: Update Grub and Reboot if Necessary
      ansible.builtin.meta: flush_handlers

    - name: Download TrueNAS ISO
      ansible.builtin.command:
        cmd: "wget -O /var/lib/vz/template/iso/TrueNAS-13.0-U6.7.iso https://download-core.sys.truenas.net/13.0/STABLE/U6.7/x64/TrueNAS-13.0-U6.7.iso"
      args:
        creates: /var/lib/vz/template/iso/TrueNAS-13.0-U6.7.iso

    - name: Detect SATA Controller
      ansible.builtin.shell:
        cmd: 'lspci -nnk | grep -i sata | grep -e "^[[:digit:]]" | cut -d " " -f 1'
      register: sata_controller
      changed_when: false

    - name: Define SATA Controller Passthrough Keys
      ansible.builtin.set_fact:
        sata_controller_keys: "{{ range(0, sata_controller.stdout_lines | length) | map('string') | map('regex_replace', '^(.*)', 'hostpci\\1') }}"

    - name: Define SATA Controller Passthrough Values
      ansible.builtin.set_fact:
        sata_controller_values: "{{ sata_controller.stdout_lines | map('regex_replace', '^(.*)', '0000:\\1') }}"

    - name: Define SATA Controller Passthrough Map
      ansible.builtin.set_fact:
        sata_controller_map: >-
          {{ sata_controller_values |
             zip(sata_controller_keys) |
             map('reverse') |
             community.general.dict }}

    - name: Create VM for TrueNAS
      community.general.proxmox_kvm:
        api_host: "nas-pve.i.krel.ing"  # TODO: use inventory_hostname?
        api_user: "root@pam"
        api_password: "{{ lookup('bitwarden.secrets.lookup', 'fdce36ca-8c9f-42d6-8343-b2a801787fad') }}"
        name: truenas
        node: nas
        vmid: 100
        sata:
          sata0: 'local-lvm:100'
          sata1: 'local:iso/TrueNAS-13.0-U6.7.iso,media=cdrom'
        net:
          net0: "virtio={{ mac_address }},bridge=vmbr0,firewall=1"
        cores: 10
        memory: 65536
        onboot: true
        ostype: other
        cpu: 'x86-64-v2-AES'
        hostpci: "{{ sata_controller_map }}"
        state: started
      delegate_to: localhost
      notify: Manual Setup

  handlers:
    - name: Update grub
      ansible.builtin.command:
        cmd: "update-grub"
      notify: Reboot

    - name: Reboot
      ansible.builtin.reboot:
        reboot_timeout: 600
        test_command: uptime

    - name: Manual Setup
      ansible.builtin.pause:
        prompt: "Please manually set up the TrueNAS VM, then press Enter to continue."
        echo: yes

