- name: Apt Update Rpic Cluster
  hosts: rpic
  gather_facts: false
  become: true  # Run as root
  tasks:
    - name: Apt update
      ansible.builtin.apt:
        update_cache: true

    - name: Apt upgrade
      ansible.builtin.apt:
        upgrade: full

    - name: Check if reboot required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists

    - name: Apt autoremove
      ansible.builtin.apt:
        autoremove: true
