- name: Get Uptime
  hosts: rpic
  tasks:
    - name: Read uptimes
      ansible.builtin.shell: cut -d ' ' -f 1 /proc/uptime
      register: uptime
      # Ansible can't detect the changed status of shell commands very
      # accurately, so we hint that this will never result in a change.
      changed_when: false

    - name: Print Message
      ansible.builtin.debug:
        msg: "Uptime: {{ (uptime.stdout | int) }} seconds / {{ (uptime.stdout | int) / (60 * 60) }} hours"
