- name: Get Uptime
  hosts: rpic
  gather_facts: false
  tasks:
    - name: Read uptimes # noqa: command-instead-of-shell
      ansible.builtin.shell: uptime -p
      register: uptime
      # Ansible can't detect the changed status of shell commands very
      # accurately, so we hint that this will never result in a change.
      changed_when: false

    - name: Print Message
      ansible.builtin.debug:
        msg: "Uptime: {{ uptime.stdout }}"
