- name: Set CLICOLOR env variable
  ansible.builtin.lineinfile:
    path: ~/.zshenv
    line: 'export CLICOLOR=auto'
    create: true
    mode: "0644"
    regexp: '^export CLICOLOR='

- name: Set LSCOLORS env variable
  ansible.builtin.lineinfile:
    path: ~/.zshenv
    line: 'export LSCOLORS=Gxfxcxdxbxegedabagacad'
    create: true
    mode: "0644"
    regexp: '^export LSCOLORS='
