- name: Config
  hosts: truenas

  roles:
    - ssh_server
    - tls_cert_push

  tasks:
    - name: create groups
      arensb.truenas.group:
        name: "{{ item }}"
        state: present
      loop:
        - "media_readonly"
        - "media_readwrite"
        - "dev_readwrite"
        - "certs_readwrite"
        - "certs_readonly"

    - name: create users
      arensb.truenas.user:
        name: "{{ item.user }}"
        comment: "{{ item.user }}"
        password: "{{ lookup('bitwarden.secrets.lookup', item.password_id) }}"
        groups: "{{ item.groups | default([]) }}"
        home: "/nonexistent"
        shell: "/usr/local/bin/bash"
        state: present
      loop:
        - user: mbair
          password_id: 369cbb03-0d0e-40fb-a0b9-b2b100189aea
          groups:
            - media_readwrite
            - dev_readwrite
        - user: ripper
          password_id: 23b52464-2823-4a8c-b12d-b226005e1616
          groups:
            - media_readwrite
        - user: kodi
          password_id: 9181f7ff-7e6a-4038-8e08-b2b1001a066c
          groups:
            - media_readonly
        - user: dev
          password_id: 1f341f46-846e-450f-8938-b2cc011bb849
          groups:
            - dev_readwrite
            - certs_readwrite
            - media_readwrite
        - user: certbot
          password_id: 177d591f-fc2f-466b-9f7c-b2d0003349d0
          groups:
            - certs_readwrite
        - user: certs_deploy
          password_id: cf980f96-40bb-4cb6-bdf9-b2d00033795b
          groups:
            - certs_readonly
        - user: gamespc
          password_id: 469c6ab1-24ac-4efc-8bf6-b2f6006239a2
          groups:
            - media_readwrite

        