- name: Config
  hosts: slothair

  vars_prompt:
    - name: ansible_become_password
      prompt: sudo password
      private: true

  vars:
    mas_installed_apps:
      # TODO: update docs for this ... their default example is broken.
      # Note that only previously installed apps will be reinstallable.
      - {id: 585829637, name: "Todoist"}
      - {id: 1352778147, name: "Bitwarden"}

    homebrew_cask_apps:
      - docker
      - vlc
      - visual-studio-code
      - obsidian

    ansible_become_password: "{{ ansible_become_password }}"
    mas_signin_dialog: true
    mas_signin_user: "krelinga@gmail.com"

  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas

  tasks:
    - name: Set OSX Defaults
      community.general.osx_defaults:
        domain: "{{ item.domain }}"
        key: "{{ item.key }}"
        type: "{{ item.type }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - domain: "Apple Global Domain"
          key: "com.apple.swipescrolldirection"
          type: boolean
          value: false
        - domain: "Apple Global Domain"
          key: "com.apple.sound.beep.volume"
          type: float
          value: 0
