- name: Config
  hosts: slothair

  vars_prompt:
    - name: ansible_become_password
      prompt: sudo password
      private: true

  vars:
    mas_installed_apps:
      # TODO: update docs for this ... their default example is broken.
      # Note that only previously installed apps will be reinstallable.
      # Until https://github.com/mas-cli/mas/issues/321 is fixed I won't be
      # able to install apps intended for iphone or ipad.
      - {id: 585829637, name: "Todoist"}
      - {id: 1352778147, name: "Bitwarden"}
      - {id: 1246969117, name: "Steam Link"}

    homebrew_cask_apps:
      - docker
      - vlc
      - visual-studio-code
      - obsidian
      - balenaetcher
      - discord
      - handbrake
      - kodi
      - raspberry-pi-imager
      - shapr3d
      - signal
      - steam
      - tailscale
      - tinymediamanager
      - zoom
      - iterm2

    homebrew_installed_packages:
      - openjdk  # needed for TinyMediaManager

    ansible_become_password: "{{ ansible_become_password }}"
    mas_signin_dialog: true
    mas_signin_user: "krelinga@gmail.com"

  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas
    - ssh_server

  tasks:
    - name: Set up Java symlink
      become: yes
      ansible.builtin.file:
        src: /opt/homebrew/opt/openjdk/libexec/openjdk.jdk
        dest: /Library/Java/JavaVirtualMachines/openjdk.jdk
        state: link
        owner: root
        group: wheel
        mode: 0755

    - name: Create tinyMediaManager directories
      ansible.builtin.file:
        path: "/Users/{{ ansible_user }}/Movies/{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "tmm_movies"
        - "tmm_shows"

    - name: Create homedir folders
      ansible.builtin.file:
        path: "/Users/{{ ansible_user }}/{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "macbin"
        - "root_links"
        - "root_links/host"
        - "root_links/nas"
        - "test"

    - name: Create Root Links
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "/Users/{{ ansible_user }}/root_links/{{ item.dest }}"
        state: link
        mode: "0755"
      loop:
        - { dest: "host/Movies", src: "/Users/{{ ansible_user }}/Movies/" }
        - { dest: "host/macbin", src: "/Users/{{ ansible_user }}/macbin/" }
        - { dest: "host/test", src: "/Users/{{ ansible_user }}/test/" }
        - { dest: "nas/media", src: "/Volumes/media/" }

    - name: Write links to root filesystem
      become: true
      ansible.builtin.copy:
        dest: "/etc/synthetic.conf"
        content: "host\t/Users/{{ ansible_user }}/root_links/host\n\
          nas\t/Users/{{ ansible_user }}/root_links/nas\n"
        mode: "0644"
        owner: root
        group: wheel

    - name: Update zsh PATH variable
      ansible.builtin.lineinfile:
        line: "{{ item }}"
        state: present
        path: "/Users/{{ ansible_user }}/.zshenv"
      loop:
        - 'export PATH="$PATH:/Users/{{ ansible_user }}/macbin"'
        - 'export PATH="$PATH:/opt/homebrew/bin"'